extends:
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  complexity:
    - error
    - 10
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
  import/no-unresolved: 0 # Turn off "Unable to resolve path to module ..." error
  import/extensions: 0 # Turn off "Missing file extension for ..." error
env:
  browser: true
  jest/globals: true
settings: {}
